# Site settings
title: Data Science & Innovation Blog
email: your.email@example.com
description: >-
  Exploring the frontiers of data science, machine learning, and innovation.
  Sharing insights, experiments, and discoveries in the world of data.
baseurl: ""
url: "http://localhost:4000"

# Author information
author:
  name: Your Name
  email: your.email@example.com
  bio: Data Scientist & Innovation Enthusiast
  avatar: "/assets/images/profile.svg"
  linkedin: your-linkedin
  github: your-github
  twitter: your-twitter

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:name/

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Theme colors and customization
theme_config:
  primary_color: "#2c3e50"
  accent_color: "#3498db"
  text_color: "#2c3e50"
  background_color: "#ffffff"
  sidebar_color: "#ecf0f1"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contact/

# Search
search: true

# Comments (optional - can be enabled later)
comments: false

# Analytics (optional - can be enabled later)
google_analytics: ""