# Site settings
title: Momchil's Blog
email: your.email@example.com
description: >-
  Free thought dumping about data science and nerdy things.
baseurl: "/mlg" # Must match your repository name for project sites
url: "" # Will be set automatically by GitHub Pages

# Author information
author:
  name: Momchil Georgiev
  email: m.georgiev@vvv-agency.com
  bio: Data Scientist & Business Owner
  avatar: "/assets/images/profile.jpg"
  linkedin: momchil-georgiev/
  github: momchilgeorgiev

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:name/

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CUSTOMIZATION.md

# GitHub Pages compatible settings

# Theme colors and customization
theme_config:
  primary_color: "#2c3e50"
  accent_color: "#3498db"
  text_color: "#2c3e50"
  background_color: "#ffffff"
  sidebar_color: "#ecf0f1"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contact/

# Search
search: true

# Comments (optional - can be enabled later)
comments: false

# Analytics (optional - can be enabled later)
google_analytics: ""

# Show future posts
future: true